version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: akrossapi_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=akrossapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
