spring:
  application:
    name: akrossapi
  datasource:
    url: jdbc:postgresql://localhost:5432/akrossapi
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect